################################################################################
# ANSIBLE configuration file to setup workstation softwares and configurations #
################################################################################

---
- hosts: local
  connection: local
  become: yes
  vars_files:
    - vars.yml

  # tasks:
  #   - shell: sudo apt-get update -y
  #   - shell: sudo apt-get dist-upgrade -y -v

  roles:
    - role: git
    - role: bash
    - role: ssh
    - role: python
    - role: apps
    - role: atom
    - role: chromium
    - role: libreoffice
    - role: nodejs
    - role: pip
    - role: sublime
