################################################################################
# ANSIBLE configuration file to setup workstation softwares and configurations #
################################################################################

---
- hosts: local
  connection: local
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - include: roles/system.yml
    - include: roles/apps.yml
    - include: roles/pip.yml
