# Install and configure softwares

- name: install git
  package:
    name: git
    state: latest

- name: install nano
  package:
    name: nano
    state: latest

- name: install python
  package:
    name: python
    state: latest

- name: install python3
  package:
    name: python3
    state: latest

- name: install python3-pip
  package:
    name: python3-pip
    state: latest

- name: install chromium-browser
  package:
    name: chromium
    state: latest

- name: install firefox
  package:
    name: firefox
    state: latest

- name: install slack
  package:
    name: slack
    state: latest

- name: install atom
  package:
    name: atom
    state: latest

- name: install filezilla
  package:
    name: filezilla
    state: latest

- name: install postman
  package:
    name: postman
    state: latest
