---
- name: Install python packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  become: yes
  with_items:
    - python
    - python3
    - python3-pip
    - python3-dev

- name: Install python-opencv
  package:
    name: python-opencv
    state: latest
