---
- name: Install git
  package:
    name: git
    state: latest

- name: Update submodules
  shell: "git submodule update --recursive --remote"

- name: Restore gitconfig
  copy:
    src: "{{ git.config.src }}{{ git.config.filename }}"
    dest: "{{ git.config.dest }}{{ git.config.filename }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
