---
- name: Add Atom repository (Webupd8team)
  apt_repository: repo="ppa:webupd8team/atom" state=present

- name: Install Atom text editor
  apt: name=atom state=present update_cache=yes

- template:
    src: "../templates/{{ atom.config.filename }}"
    dest: "{{ atom.config.path }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664

- name: Install Atom packages
  command: sudo apm install --packages-file {{ atom.packages.path }}
