# Install and configure softwares

- name: install git
  package:
    name: git
    state: latest

- name: install nano
  package:
    name: nano
    state: latest

- name: Install Chromium
  package:
    name: chromium-browser
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  command: update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/chromium-browser 250

- name: install firefox
  package:
    name: firefox
    state: latest

- name: install filezilla
  package:
    name: filezilla
    state: latest

- name: install postman
  package:
    name: postman
    state: latest

- name: install slack
  package:
    name: slack
    state: latest
