# Install apps
#
# This role should be eliminated whenever one of these apps require more than one task

---
- name: Install system apps
  apt: pkg={{ item }} state=latest
  with_items:
    - nano
    - less
    - htop
    - tree

- name: Install other apps
  apt: pkg={{ item }} state=latest
  with_items:
    - firefox
    - filezilla
    - slack
